# Generated by Django 3.0 on 2023-08-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntiqueStoreApp', '0002_auto_20230821_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiqueitem',
            name='image',
            field=models.ImageField(null=True, upload_to='antiques/'),
        ),
    ]
