# Generated by Django 3.0 on 2023-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntiqueStoreApp', '0004_antiqueitem_maximumprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiqueitem',
            name='TagLine',
            field=models.CharField(default='Antique', max_length=200),
        ),
        migrations.AddField(
            model_name='antiqueitem',
            name='itemtype',
            field=models.CharField(choices=[('Antique', 'Antique'), ('Arts', 'Arts'), ('HandiCrafts', 'HandiCrafts'), ('Jewelry', 'Jewelry')], default='0', max_length=100),
        ),
    ]
