# Generated by Django 3.0 on 2023-08-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntiqueStoreApp', '0005_auto_20230823_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cno', models.CharField(max_length=200)),
                ('cemail', models.CharField(max_length=200)),
                ('caddress', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='antiqueitem',
            name='TagLine',
            field=models.CharField(default='', max_length=200),
        ),
    ]
