# Generated by Django 3.0 on 2023-08-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AntiqueStoreApp', '0006_auto_20230824_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
