# Generated by Django 3.0 on 2023-09-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntiqueStoreApp', '0007_delete_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_amount',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
