# Generated by Django 3.0 on 2023-09-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntiqueStoreApp', '0009_auto_20230908_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
